### ISSUE TITLE
“Panama Papers” inquiry

### ISSUE THREAD

**Issue by Snekili** [official-inquiries/official-inquiries.com#69]
European Union

The European Parliament agreed to set up an inquiry committee into the “Panama Papers” revelations, of detailed information on offshore companies and their ultimate beneficiaries, in a vote on Wednesday. The committee is to investigate alleged contraventions and maladministration in the application by the EU Commission or member states of EU laws on money laundering, tax avoidance and tax evasion. It will have 65 members and twelve months to present its report.

The European Parliament Conference of Presidents (EP President and political group leaders), agreed the committee’s mandate on Thursday 2 June.

[Announcement](http://www.europarl.europa.eu/news/en/news-room/20160603IPR30203/Parliament-sets-up-%E2%80%9CPanama-Papers%E2%80%9D-inquiry-committee)

**Comment by GregoryRhysEvans** [comment]
Since this inquiry hasn't even started yet, it's probably not one we are interested in for now.
