### ISSUE TITLE
Website architecture

### ISSUE THREAD

**Issue by GregoryRhysEvans** [official-inquiries/official-inquiries.com#72]
## Potential website architecture:
- Main Page
  - Browse reports
    - [Country]
      - Report year/name/body [link to readme] [link to originals] [link to text]
    - [Country]
      - Report year/name/body [link to readme] [link to originals] [link to text]
- Search reports
  - Search
- About us
- Get Involved

**Comment by rufuspollock** [comment]
DUPLICATE of https://github.com/official-inquiries/official-inquiries.com/issues/3
